name: Generate PDF from HTML
on:
  push:
    branches:
      - data_analyst
jobs:
  generate-pdf:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: html to pdf
        uses: fifsky/html-to-pdf-action@master
        with:
          htmlFile: index.html
          outputFile: resume.pdf
          pdfOptions: '{"width": "22cm", "height": "29.7cm", "displayHeaderFooter": true, "scale": 0.5, "printBackground":true, "margin": {"top": "5mm", "left": "5mm", "right": "5mm", "bottom": "5mm"}}'
      - name: Upload PDF artifact
        uses: actions/upload-artifact@v4
        with:
          name: resume
          path: resume.pdf
